name: "cert module test"

on:
  pull_request:
    branches: [main]
    path:
      - cert/**
  workflow_dispatch:

jobs:
  validation:
    runs-on: ubuntu-latest
    env:
      TF_LOG: INFO
    defaults:
      run:
        working-directory: ./cert
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9

      # Validate Terraform files
      - run: terraform fmt -check -recursive
      - run: terraform init
      - run: terraform validate -no-color

  unit-test:
    needs: validation
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cert/test
    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Run unit test
        run: go test -v
        env:
          FASTLY_API_KEY: ${{ secrets.FASTLY_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
